### PR TITLE
mypy: check untyped tests

### PR DESCRIPTION
**Pull request by asottile**
This aims to make #81 easier or not-required, notably mypy is now type-checking tests without the need to annotate them.

### CODE REVIEW

**Comment by asottile** [comment]
uh weird, not sure why this passed locally and now is not passing locally -- I'll take a look at that \*head scratches\*

**Comment by asottile** [comment]
🤦‍♂️ oh I was running mypy before I had the dependencies installed

**Comment by asottile** [comment]
ok, should be passing now -- I needed to make the fake types extend the real types to trick mypy.  I guess this could use protocols but I wanted to keep it ~mostly simple and without requiring [PEP 544](https://www.python.org/dev/peps/pep-0544/)

**Comment by brettcannon** [comment]
A quick look makes it all look reasonable, but the branch is out-of-date now. Could you bring it into sync, @asottile? Then I can give it a review.

**Comment by asottile** [comment]
@brettcannon no problem, just clicked the "Update to master" button on github -- looks like @.Mariatta hit it a few days ago as well 🎉

**Comment by brettcannon** [comment]
LGTM! Thanks, @asottile !

@Mariatta would you mind double-checking me since I don't want to break the CLA bot unnecessarily? 😉

**Comment by Mariatta** [comment]
Thanks!

**Pull request merged**
